import {
  MatAutocompleteModule,
  MatButtonModule,
  MatCardModule,
  MatDialogModule,
  MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatMenuModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatSliderModule,
  MatSnackBarModule,
  MatTooltipModule,
  MatTableModule,
  MatChipsModule,
  MatBadgeModule,
  MatTreeModule,
  MatExpansionModule,
  MatSelectModule,
  MatTabsModule,
  MatRadioModule,
} from '@angular/material';
import {NgModule} from '@angular/core';

@NgModule({
  imports: [
    MatButtonModule,
    MatMenuModule,
    MatIconModule,
    MatCardModule,
    MatSliderModule,
    MatProgressBarModule,
    MatAutocompleteModule,
    MatInputModule,
    MatGridListModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MatTooltipModule,
    MatListModule,
    MatDialogModule,
    MatTableModule,
    MatChipsModule,
    MatBadgeModule,
    MatTreeModule,
    MatExpansionModule,
    MatSelectModule,
    MatTabsModule,
    MatRadioModule,
  ],
  exports: [
    MatButtonModule,
    MatMenuModule,
    MatIconModule,
    MatCardModule,
    MatSliderModule,
    MatProgressBarModule,
    MatAutocompleteModule,
    MatInputModule,
    MatGridListModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MatTooltipModule,
    MatListModule,
    MatDialogModule,
    MatTableModule,
    MatChipsModule,
    MatBadgeModule,
    MatTreeModule,
    MatExpansionModule,
    MatSelectModule,
    MatTabsModule,
    MatRadioModule,
  ],
})

export class MaterialModule {
}
