#.travis.yml

dist: trusty

sudo: required

language: node_js

branches:
  only:
    - master

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

before_install:
  - 'set -e'
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'phantomjs --version'
  - 'firefox --version'
  - 'chromium-browser --version'
  - nvm install # install version specified in file .nvmrc
  - nvm use # uses version specified in file .nvmrc
  - node --version
  - npm install -g angular-cli-ghpages

install:
  - npm install

script:
  #- npm run ci
  - npm run build-all

notifications:
  email:
    on_failure: change
    on_success: change
